package com.geyu.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.geyu.database.ben.Account;
import com.geyu.database.ben.AccountBook;
import com.geyu.database.ben.CategoryModel;
import com.geyu.database.ben.Record;

import com.geyu.database.AccountDao;
import com.geyu.database.AccountBookDao;
import com.geyu.database.CategoryModelDao;
import com.geyu.database.RecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig accountBookDaoConfig;
    private final DaoConfig categoryModelDaoConfig;
    private final DaoConfig recordDaoConfig;

    private final AccountDao accountDao;
    private final AccountBookDao accountBookDao;
    private final CategoryModelDao categoryModelDao;
    private final RecordDao recordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        accountBookDaoConfig = daoConfigMap.get(AccountBookDao.class).clone();
        accountBookDaoConfig.initIdentityScope(type);

        categoryModelDaoConfig = daoConfigMap.get(CategoryModelDao.class).clone();
        categoryModelDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        accountBookDao = new AccountBookDao(accountBookDaoConfig, this);
        categoryModelDao = new CategoryModelDao(categoryModelDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(AccountBook.class, accountBookDao);
        registerDao(CategoryModel.class, categoryModelDao);
        registerDao(Record.class, recordDao);
    }
    
    public void clear() {
        accountDaoConfig.clearIdentityScope();
        accountBookDaoConfig.clearIdentityScope();
        categoryModelDaoConfig.clearIdentityScope();
        recordDaoConfig.clearIdentityScope();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public AccountBookDao getAccountBookDao() {
        return accountBookDao;
    }

    public CategoryModelDao getCategoryModelDao() {
        return categoryModelDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

}
